### ISSUE TITLE
Add placeholder to "add" input field

### ISSUE THREAD

**Issue by raucao** [bumi/about.bit#5]
It wasn't immediately clear to me what to add, but as I knew a bit about the app already, it quickly came to me that it must be the Namecoin username/ID. Maybe add it as a placeholder attribute to the input element?

**Comment by bumi** [comment]
thanks, good idea. 
It for sure is a problem because probably a lot of people do not know the IDs of any contact. 

I've added a placeholder and a tooltip with the hint to a profile for people who want to try it but do not know a contact.

**Comment by raucao** [comment]
Haha, it doesn't fit my screen so it says "try bum". :)

**Comment by bumi** [comment]
arg, looked fine here. I really need to relearn me some CSS :) 
for now I made the text shorter. thanks.
